language: ruby
rvm:
  - 2.4.0
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
script:
  - bundle exec rspec spec/
services:
  - postgresql
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database myapp_test' -U postgres
  - "rake db:migrate"
